### ISSUE TITLE
valid paths can contain brackets

### ISSUE THREAD

**Issue by es128** [jonschlinkert/is-invalid-path#1]
https://github.com/paulmillr/chokidar/issues/230

**Comment by jonschlinkert** [comment]
But not "safe" paths. I considered calling this `is-unsafe-path`, but some of the characters are completely invalid, some unsafe (maybe I should just split out the "unsafe" versus "invalid" into two libs?). 

In node.js, IMHO the safe route is to assume that any path may become part of a URL. [RFC 1738 states](https://www.ietf.org/rfc/rfc1738.txt):

> Other characters are unsafe because gateways and other transport agents are known to sometimes modify such characters. These characters are `{`, `}`, `|`, `\`, `^`, `~`, `[`, `]`, and <code>`</code>

**Comment by es128** [comment]
I think separating safe vs valid makes sense.

Just wanted to bring to your attention that assuming a glob-like path can't be a filename can lead to bad consequences.

**Comment by jonschlinkert** [comment]
> I think separating safe vs valid makes sense.

k, I agree 

> assuming a glob-like path can't be a filename can lead to bad consequences.

this is why the extended globbing features are disabled by default :)

**Comment by jonschlinkert** [comment]
thanks for bringing this up, you're right. I'll split them out

**Comment by es128** [comment]
> this is why the extended globbing features are disabled by default :)

They are? I never added an option in anymatch to explicitly enable them and they seem to work. Also, minimatch seems to turn on all the extended stuff by default with the option to disable some of it, although character sets in brackets isn't one of the disable-able features.

**Comment by jonschlinkert** [comment]
oh, wait. maybe that was in the the code that we haven't merged? that or I didn't merge those settings when I read your comment about not disabling by default. https://github.com/jonschlinkert/micromatch/issues/27#issue-69432045.

**Comment by es128** [comment]
Yeah I was advocating for enabling everything by default, but it's possible that's naive. Latest published version at least seems to handle at least basic cases of brackets, extglobs, and braces by default iirc.

**Comment by jonschlinkert** [comment]
well, then we're both naive lol. I think you're right still, I like the idea of having them on by default, I just want to make sure users get what they expect
